In [1]:

import pandas as pd

In [2]:
import os

print("Current working folder:")
print(os.getcwd())

print("\nFiles and folders here:")
print(os.listdir())

Current working folder:
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\notebook

Files and folders here:
['data_preprocessing.ipynb', 'numerical_analysis.ipynb']

In [3]:

from pathlib import Path

project_folder = Path.cwd().parent

print("Project folder:", project_folder)
print("\nCSV files found:")

for file in project_folder.rglob("*.csv"):
    print(file)

Project folder: c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction

CSV files found:
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\cleaned_churn_data.csv
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\Customer-Churn-Prediction.csv

In [5]:

from pathlib import Path

project_folder = Path.cwd().parent

print("Project folder:", project_folder)
print("\nFolders inside project:")

for item in project_folder.iterdir():
    print(item.name, "(folder)" if item.is_dir() else "(file)")

print("\nCSV files found inside project:")

csv_files = list(project_folder.rglob("*.csv"))

if csv_files:
    for file in csv_files:
        print(file)
else:
    print("No CSV files found in this project folder.")

Project folder: c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction

Folders inside project:
.vscode (folder)
app (folder)
data (folder)
model (folder)
notebook (folder)
README.md (file)
src (folder)

CSV files found inside project:
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\cleaned_churn_data.csv
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\Customer-Churn-Prediction.csv

In [7]:

from pathlib import Path

project_folder = Path.cwd().parent

print("Project folder:", project_folder)
print("\nCSV files found:")

for file in project_folder.rglob("*"):
    if file.is_file() and file.suffix.lower() == ".csv":
        print(file)

Project folder: c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction

CSV files found:
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\cleaned_churn_data.csv
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\Customer-Churn-Prediction.csv

In [8]:

from pathlib import Path

project_folder = Path.cwd().parent

csv_files = [
    file for file in project_folder.rglob("*")
    if file.is_file() and file.suffix.lower() == ".csv"
]

if csv_files:
    for i, file in enumerate(csv_files, start=1):
        print(f"{i}. {file}")
else:
    print("No CSV files found in the project folder.")
    print("Please check the VS Code Explorer for your CSV file.")

1. c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\cleaned_churn_data.csv
2. c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\Customer-Churn-Prediction.csv

In [9]:

from pathlib import Path

desktop = Path.home() / "OneDrive" / "Desktop"

if not desktop.exists():
    desktop = Path.home() / "Desktop"

print("Searching:", desktop)

for file in desktop.rglob("*.csv"):
    print(file)

Searching: C:\Users\Rakshitha Srinivasa\OneDrive\Desktop
C:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\cleaned_churn_data.csv
C:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\Customer-Churn-Prediction.csv

In [11]:

from pathlib import Path

# Search your Customer-Churn-Prediction project
project = Path.cwd().parent

print("Project folder:", project)
print("Project folder exists:", project.exists())

print("\nFiles and folders:")
for item in project.iterdir():
    print(item.name)

print("\nCSV files:")
for file in project.rglob("*.csv"):
    print(file)

Project folder: c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction
Project folder exists: True

Files and folders:
.vscode
app
data
model
notebook
README.md
src

CSV files:
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\cleaned_churn_data.csv
c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\Customer-Churn-Prediction.csv

In [12]:

import pandas as pd
from pathlib import Path

project_folder = Path.cwd().parent

csv_path = project_folder / "data" / "cleaned_churn_data.csv"

df = pd.read_csv(csv_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (7043, 26)

,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,CLTV
0,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,3239
1,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,2701
2,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,5372
3,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,5003
4,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,5340

In [13]:

import pandas as pd
from pathlib import Path

project_folder = Path.cwd().parent

csv_path = project_folder / "data" / "cleaned_churn_data.csv"

df = pd.read_csv(csv_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (7043, 26)

,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,CLTV
0,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,3239
1,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,2701
2,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,5372
3,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,5003
4,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,5340

In [14]:

import pandas as pd
from pathlib import Path

project_folder = Path.cwd().parent
csv_path = project_folder / "data" / "cleaned_churn_data.csv"

df = pd.read_csv(csv_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
display(df.head())

Dataset loaded successfully!
Shape: (7043, 26)

,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,CLTV
0,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,3239
1,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,2701
2,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,5372
3,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,5003
4,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,5340

In [15]:

# Check missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

# Check total missing values
print("\nTotal missing values:", df.isnull().sum().sum())

Missing values in each column:
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
CLTV                 0
dtype: int64

Total missing values: 0

In [16]:

# Count duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [17]:

# Display column names
print(df.columns.tolist())

# Find TotalCharges even if the column has a space
total_col = next(
    (col for col in df.columns
     if col.strip().lower().replace(" ", "") == "totalcharges"),
    None
)

if total_col is not None:
    print("\nColumn found:", total_col)
    print("Data type before conversion:", df[total_col].dtype)

    # Convert to numeric; invalid values become NaN
    df[total_col] = pd.to_numeric(
        df[total_col].astype(str).str.strip().replace("", pd.NA),
        errors="coerce"
    )

    print("Data type after conversion:", df[total_col].dtype)
    print("Missing values after conversion:", df[total_col].isna().sum())
else:
    print("\nTotalCharges column not found.")

['City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'CLTV']

Column found: Total Charges
Data type before conversion: str
Data type after conversion: float64
Missing values after conversion: 11

In [18]:

# Check missing values before handling
print("Missing values before handling:")
print(df.isnull().sum())

# Remove rows only if the Churn target is missing
churn_col = next(
    (col for col in df.columns if col.strip().lower() == "churn"),
    None
)

if churn_col is not None:
    df = df.dropna(subset=[churn_col])

# Fill missing numeric values with the median
# Fill missing categorical values with the most frequent value
for col in df.columns:
    if col == churn_col:
        continue

    if df[col].isnull().any():
        if pd.api.types.is_numeric_dtype(df[col]):
            median_value = df[col].median()
            if pd.notna(median_value):
                df[col] = df[col].fillna(median_value)
        else:
            mode_values = df[col].mode(dropna=True)
            if not mode_values.empty:
                df[col] = df[col].fillna(mode_values.iloc[0])

print("\nMissing values after handling:")
print(df.isnull().sum())

Missing values before handling:
City                  0
Zip Code              0
Lat Long              0
Latitude              0
Longitude             0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Label           0
CLTV                  0
dtype: int64

Missing values after handling:
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
CLTV                 0
dtype: int64

In [19]:

# Remove exact duplicate rows
df = df.drop_duplicates()

# Save the processed dataset
output_path = project_folder / "data" / "processed_churn_data.csv"

df.to_csv(output_path, index=False)

print("Processed dataset saved successfully!")
print("Saved to:", output_path)
print("Final dataset shape:", df.shape)
print("Remaining missing values:", df.isnull().sum().sum())
print("Remaining duplicate rows:", df.duplicated().sum())

Processed dataset saved successfully!
Saved to: c:\Users\Rakshitha Srinivasa\OneDrive\Desktop\Customer-Churn-Prediction\data\processed_churn_data.csv
Final dataset shape: (7043, 26)
Remaining missing values: 0
Remaining duplicate rows: 0

In [20]:

from pathlib import Path
import pandas as pd

output_path = project_folder / "data" / "processed_churn_data.csv"

if output_path.exists():
    processed_df = pd.read_csv(output_path)

    print("SUCCESS: Processed dataset exists!")
    print("Dataset shape:", processed_df.shape)
    print("Missing values:", processed_df.isnull().sum().sum())
    print("Duplicate rows:", processed_df.duplicated().sum())

    print("\nColumn data types:")
    print(processed_df.dtypes)

    display(processed_df.head())
else:
    print("Processed file not found.")
    print("Run the Save Processed Dataset cell first.")

SUCCESS: Processed dataset exists!
Dataset shape: (7043, 26)
Missing values: 0
Duplicate rows: 0

Column data types:
City                     str
Zip Code               int64
Lat Long                 str
Latitude             float64
Longitude            float64
Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges        float64
Churn Label              str
CLTV                   int64
dtype: object

,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,CLTV
0,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,3239
1,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,2701
2,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,5372
3,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,5003
4,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,5340

print("Dataset shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("TotalCharges type:", df[total_col].dtype)
print("Output file exists:", output_path.exists())

In [21]:
print("Dataset shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("TotalCharges type:", df[total_col].dtype)
print("Output file exists:", output_path.exists())

Dataset shape: (7043, 26)
Missing values: 0
Duplicate rows: 0
TotalCharges type: float64
Output file exists: True